//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdj3course.testReferance {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webServiceSJ3Course", ConfigurationName="testReferance.testMethod")]
    public interface testMethod {
        
        // CODEGEN: Generating message contract since element name getContReturn from namespace http://webServiceSJ3Course is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        sdj3course.testReferance.getContResponse getCont(sdj3course.testReferance.getContRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sdj3course.testReferance.getContResponse> getContAsync(sdj3course.testReferance.getContRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getContRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCont", Namespace="http://webServiceSJ3Course", Order=0)]
        public sdj3course.testReferance.getContRequestBody Body;
        
        public getContRequest() {
        }
        
        public getContRequest(sdj3course.testReferance.getContRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getContRequestBody {
        
        public getContRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getContResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getContResponse", Namespace="http://webServiceSJ3Course", Order=0)]
        public sdj3course.testReferance.getContResponseBody Body;
        
        public getContResponse() {
        }
        
        public getContResponse(sdj3course.testReferance.getContResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webServiceSJ3Course")]
    public partial class getContResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getContReturn;
        
        public getContResponseBody() {
        }
        
        public getContResponseBody(string getContReturn) {
            this.getContReturn = getContReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface testMethodChannel : sdj3course.testReferance.testMethod, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class testMethodClient : System.ServiceModel.ClientBase<sdj3course.testReferance.testMethod>, sdj3course.testReferance.testMethod {
        
        public testMethodClient() {
        }
        
        public testMethodClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public testMethodClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public testMethodClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public testMethodClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdj3course.testReferance.getContResponse sdj3course.testReferance.testMethod.getCont(sdj3course.testReferance.getContRequest request) {
            return base.Channel.getCont(request);
        }
        
        public string getCont() {
            sdj3course.testReferance.getContRequest inValue = new sdj3course.testReferance.getContRequest();
            inValue.Body = new sdj3course.testReferance.getContRequestBody();
            sdj3course.testReferance.getContResponse retVal = ((sdj3course.testReferance.testMethod)(this)).getCont(inValue);
            return retVal.Body.getContReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sdj3course.testReferance.getContResponse> sdj3course.testReferance.testMethod.getContAsync(sdj3course.testReferance.getContRequest request) {
            return base.Channel.getContAsync(request);
        }
        
        public System.Threading.Tasks.Task<sdj3course.testReferance.getContResponse> getContAsync() {
            sdj3course.testReferance.getContRequest inValue = new sdj3course.testReferance.getContRequest();
            inValue.Body = new sdj3course.testReferance.getContRequestBody();
            return ((sdj3course.testReferance.testMethod)(this)).getContAsync(inValue);
        }
    }
}
